### ISSUE TITLE
The atan2(x,y) function seems to be wrong

### ISSUE THREAD

**Issue by cuphyalex** [osiris-code/osiris-code.github.io#1]
Hello,

I am a new user. When I type in the function atan2(x,y) as told on the page of "Analytical Function Parser", I got arctan(x/y) instead of arctan(y/x). I plotted the graph to verify my thought, which seems to be right and the description in "Analytical Function Parser" is wrong.

**Comment by ricardo-fonseca** [comment]
Hi, thanks for spotting this, it is actually an error in the documentation, the function that is implemented is actually `atan2(y,x)`, just like the equivalent `C` function. I've corrected the documentation.
