### ISSUE TITLE
Inquiry Regarding the Consideration of Brownian Motion (or other types of randomness) in the Simulation Process

### ISSUE THREAD

**Issue by chuan-liu6** [osiris-code/osiris-code.github.io#3]
Have you considered incorporating Brownian motion or other forms of randomness in the PIC simulation to model the stochastic behavior of particles?

**Comment by ricardo-fonseca** [comment]
Some users have played with this, essentially by replacing the particle pusher with a custom one, but there are no plans to add any such feature to the code.
